version: "3"
services:
  app:
    build: .
    container_name: rudl
    environment:
      - ENV
      - DOMAIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/root/letsencrypt
      - ./.cache:/root/.cache
      - ./server:/root/app/server
      - ./client:/root/app/client
      - ./run:/root/app/run
      - ./yarn.lock:/root/app/yarn.lock
      - ./db/files:/root/app/db/files
      - ./logs:/root/app/logs
    depends_on:
      - redis
      - neo4j
  redis:
    image: redis
    volumes:
      - ./db/redis:/data
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/neo4j/data:/var/lib/neo4j/data
      - ./db/neo4j/conf:/var/lib/neo4j/conf
      - ./db/neo4j/logs:/var/lib/neo4j/logs
