version: "3"
services:
  app:
    build: .
    container_name: rudl
    environment:
      - ENV
      - LANGUAGE
      - DOMAIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.cache:/root/.npm
      - ./.env:/root/app/.env
      - ./server:/root/app/server
      - ./client:/root/app/client
      - ./run:/root/app/run
      - ./test:/root/app/test
      - ./letsencrypt:/root/app/letsencrypt
      - ./logs:/root/app/logs
      - ./package-lock.json:/root/app/package-lock.json
      - ./db/files:/root/app/db/files
    depends_on:
      - redis
      - neo4j
  redis:
    image: redis
    volumes:
      - ./db/redis:/data
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/neo4j/conf:/var/lib/neo4j/conf
      - ./db/neo4j/data:/var/lib/neo4j/data
      - ./db/neo4j/plugins:/plugins
      - ./db/neo4j/logs:/logs
