version: '2'

services:
  app:
    build: .
    container_name: meal2share
    environment:
      - ENV
    ports:
      - "80:80"
      - "5858:5858"
    volumes:
      - ./server:/home/app/server
      - ./client:/home/app/client
      - ./run:/home/app/run
      - ./db/files:/home/app/db/files
      - ./logs:/home/app/logs
    depends_on:
      - redis
      - arango
  redis:
    image: redis
    volumes:
      - ./db/redis:/data
  arango:
    command: arangod --server.authentication-unix-sockets true
    volumes:
      - ./db/arango:/var/lib/arangodb3
    environment:
      - ARANGO_RANDOM_ROOT_PASSWORD=1
      - ARANGODB_USERNAME=meal2share
      - ARANGODB_PASSWORD=meal2share
      - ARANGODB_DBNAME=meal2share
    image: arangodb
    ports:
      - "8529:8529"
