import {User} from '../user/User';
import {Node} from '../Node';

export interface Notification {
	type: NotificationType;
	sender: User;
	subject: Node,
	unread: boolean;
	createdAt: number
}

export enum NotificationType {
	CREATES_EXPEDITION = 0,
	JOINS_EXPEDITION = 1,// TODO @ APPROVE ALL
	LEFTS_EXPEDITION = 2,
	REJECTED_FROM_EXPEDITION = 3,
	INVITED_TO_EXPEDITION = 4,
	ACCEPTS_INVITATION_FOR_EXPEDITION = 5,
	REJECTS_INVITATION_FOR_EXPEDITION = 6,
	APPLIES_FOR_EXPEDITION = 7,
	ACCEPTS_APPLICATION_FOR_EXPEDITION = 8,
	REJECTS_APPLICATION_FOR_EXPEDITION = 9,
    LIKES_RUDEL = 10,
	LIKES_USER = 11,
	COMMENTS_EXPEDITION = 12,
    EXPEDITION_IS_TODAY = 13,
    CREATES_RUDEL = 14,
    RECEIVED_EXPEDITION_RECOMMENDATION = 15,
    RECEIVED_RUDEL_RECOMMENDATION = 16 //TODO
}
